name: chatbot_social_media_2
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - nbconvert==5.6.1
  - pip=20.0.2
  - python=3.6.10
  - setuptools=45.1.0
  - matplotlib==3.1.3
  - numpy==1.18.1
  - opencv==4.2.0
  - pyaudio==0.2.11
  - pygobject==3.30.5
  - speechrecognition==3.6.3
  - urllib3==1.25.8
  - pip:
    - gtts==2.2.1
    - gtts-token==1.1.4
    - pygame==1.9.6
    - uuid==1.30