name: chatbot_social_media
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - nbconvert==5.6.1
  - pip=20.0.2
  - python=3.6.10
  - setuptools=45.1.0
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - pip:
    - gtts==2.1.1
    - gtts-token==1.1.3
    - matplotlib==3.1.3
    - numpy==1.18.1
    - opencv-python==4.2.0.32
    - playsound==1.2.2
    - pyaudio==0.2.11
    - speechrecognition==3.8.1
    - urllib3==1.25.8
    - uuid==1.30
